version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      MYSQL_ROOT_PASSWORD: ""

  nginx:
    image: local-nginx:v1
    ports:
      - 80:80
    volumes:
      - ./../php-elasticsearch/:/var/www/html/

  php:
    image: local-php:v1
    ports: 
      - 81:80
    volumes:
      - ./../php-elasticsearch/:/var/www/html/

volumes:
  portainer_data:
  mysql_data: